development:
  site: campfire_subdomain_name 
  use_ssl: true
  rooms:
  - Main room
  - Other room
  username: foo@bar.com
  nickname: Bot Name
  password: password
  twitter_feed: 'http://search.twitter.com/search.atom?q=from%3Atimriley+OR+from%3Ahughevans+OR+from%3Aschlick+OR+from%3Aseanodowd'
  twitter_hide_replies: false
  disable_plugins: 
    - bugzilla
    - jira
    - infobot
    - insult
    - signal_filter
    - twitter_echo
    - basecamp
    - unfuddle
production:
  site: campfire_subdomain_name
  use_ssl: true
  rooms:
  - Company Chat
  username: foo@bar.com
  nickname: Bot Name
  password: password
  twitter_feed: 'http://search.twitter.com/search.atom?q=from%3Atimriley+OR+from%3Ahughevans+OR+from%3Aschlick+OR+from%3Aseanodowd'
  twitter_hide_replies: false
  disable_plugins: 
    - bugzilla
    - jira
    - infobot
    - insult
    - signal_filter
    - twitter_echo
    - basecamp
    - unfuddle